# Generated by Django 5.1.3 on 2024-11-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='applied_at',
        ),
    ]
