# Generated by Django 5.1.3 on 2024-11-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_applied_on_application_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
    ]
